version: '3.8'

services:
  redis-live-data:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis-queue:
    image: redis
    ports:
      - "6380:6379"
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # postgres:
  #   image: timescale/timescaledb:latest-pg12
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_DB=forexdb
  #     - POSTGRES_USER=forexuser
  #     - POSTGRES_PASSWORD=forexpassword
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - my-network
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  postgres:
    build:
      context: ./services/postgres  # Path to the directory with your Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=forexdb
      - POSTGRES_USER=forexuser
      - POSTGRES_PASSWORD=forexpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./services/postgres/init_scripts:/docker-entrypoint-initdb.d  # Mount init scripts
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # oanda_live_data:
  #   build: 
  #     context: ./modules/LiveDataCollector/Oanda
  #   volumes:
  #     - ./modules/LiveDataCollector/Oanda/src:/usr/src/app/src
  #   ports:
  #     - "3101:3000"
  #   depends_on:
  #     - redis-live-data
  #   networks:
  #     - my-network
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

  airflow-webserver:
    build: 
      context: ./services/airflow 
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.contrib.auth.backends.password_auth
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://forexuser:forexpassword@postgres/airflowdb
      - AIRFLOW__CORE__FERNET_KEY=IEh0KyelruFu1jN4ebH-ukAlvfbW-oufei-fgc3LZfM=
    volumes:
      - ./services/airflow/dags:/opt/airflow/dags
      - ./services/airflow/logs:/opt/airflow/logs
      - ./services/airflow/plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: airflow webserver
    depends_on:
      - redis-queue
      - postgres
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  airflow-scheduler:
    build: 
      context: ./services/airflow 
    command: airflow scheduler
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://forexuser:forexpassword@postgres/airflowdb
      - AIRFLOW__CORE__FERNET_KEY=IEh0KyelruFu1jN4ebH-ukAlvfbW-oufei-fgc3LZfM=
    volumes:
      - ./services/airflow/dags:/opt/airflow/dags
      - ./services/airflow/logs:/opt/airflow/logs
      - ./services/airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis-queue
      - postgres
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  logstash:
    image: logstash:7.9.3
    ports:
      - "5000:5000"
    volumes:
      - ./services/logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - my-network
    depends_on:
      - elasticsearch
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  kibana:
    image: kibana:7.9.3
    ports:
      - "5601:5601"
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  filebeat:
    image: elastic/filebeat:8.11.3
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - my-network
    command: -e -strict.perms=false
    depends_on:
      - logstash
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"


  fastapi:
    build: ./modules/RestAPI
    networks:
      - my-network
    volumes:
      - ./modules/RestAPI/src:/app
    ports:
      - "8000:8000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  
  data_harmonizer:
    build:
      context: ./modules/DataHarmonizer
    volumes:
      - ./modules/DataHarmonizer/src:/usr/src/app/src
    user: root
    depends_on:
      - redis-live-data
      - redis-queue  
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  
  process-data:
    build:
      context: ./modules/processData
    volumes:
      - ./modules/processData/src:/usr/src/app/src
    user: root
    depends_on:
      - redis-queue  
      - postgres
    networks:
      - my-network
    environment:
      - POSTGRES_DB=forexdb
      - POSTGRES_USER=forexuser
      - POSTGRES_PASSWORD=forexpassword
      - POSTGRES_HOST=postgres
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  

  ctrader_fix_live:
    build:
      context: ./modules/LiveDataCollector/Ctrader
    volumes:
      - ./modules/LiveDataCollector/Ctrader/src:/usr/src/app/src
    user: root
    depends_on:
      - postgres
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  websocket_client:
    build:
      context: ./modules/MT5LiveDataClient
    depends_on:
      - postgres
    networks:
      - my-network
    volumes:
      - ./modules/MT5LiveDataClient/src:/usr/src/app/src
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  ctrader_hist_data:
    build:
      context: ./modules/HistoricalDataCollector/Ctrader
    volumes:
      - ./modules/HistoricalDataCollector/Ctrader/src:/usr/src/app/src
    user: root
    depends_on:
      - airflow-scheduler
    ports:
      - "5100:5100"
    networks:
      - my-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  # historical_price:
  #   build:
  #     context: ./modules/HistnoricalPriceApi
  #   volumes:
  #     - ./modules/HistoricalPriceApi/src:/usr/src/app/src
  #   user: root
  #   depends_on:
  #     - postgres
  #   networks:
  #     - my-network
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  # prometheus:
  #   image: prom/prometheus:v2.26.0
  #   volumes:
  #     - ./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - my-network
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  # supervisor:
  #   build: ./services/supervisor/  # Path to your Dockerfile
  #   ports:
  #     - "9001:9001"  # Expose Supervisor web interface
  #   volumes:
  #     - ./services/supervisor/conf.d:/etc/supervisor/conf.d  # Mount your Supervisor configuration
networks:
  my-network:
    driver: bridge

volumes:
  postgres-data:
  elasticsearch-data:
