"""Added trade_orders table

Revision ID: 0a6862dfcea1
Revises: 8be081a463bf
Create Date: 2024-03-28 09:26:51.627367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6862dfcea1'
down_revision: Union[str, None] = '8be081a463bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('price_open', sa.Float(), nullable=False),
    sa.Column('price_current', sa.Float(), nullable=True),
    sa.Column('volume_initial', sa.Float(), nullable=False),
    sa.Column('volume_current', sa.Float(), nullable=True),
    sa.Column('time_setup', sa.DateTime(), nullable=False),
    sa.Column('time_done', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('position_status', sa.Enum('open', 'closed', name='position_status_enum'), nullable=False),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('swap', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('reason', sa.Integer(), nullable=True),
    sa.Column('magic', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_orders')
    # ### end Alembic commands ###
