"""Add user_profiles table

Revision ID: 68261d929a86
Revises: ad3e4fccc7c7
Create Date: 2024-04-18 07:32:03.802516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68261d929a86'
down_revision: Union[str, None] = 'ad3e4fccc7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.BigInteger(), nullable=False),
    sa.Column('trade_mode', sa.Integer(), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('limit_orders', sa.Integer(), nullable=True),
    sa.Column('margin_so_mode', sa.Integer(), nullable=True),
    sa.Column('trade_allowed', sa.Boolean(), nullable=True),
    sa.Column('trade_expert', sa.Boolean(), nullable=True),
    sa.Column('margin_mode', sa.Integer(), nullable=True),
    sa.Column('currency_digits', sa.Integer(), nullable=True),
    sa.Column('fifo_close', sa.Boolean(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('margin_free', sa.Float(), nullable=True),
    sa.Column('margin_level', sa.Float(), nullable=True),
    sa.Column('margin_so_call', sa.Float(), nullable=True),
    sa.Column('margin_so_so', sa.Float(), nullable=True),
    sa.Column('margin_initial', sa.Float(), nullable=True),
    sa.Column('margin_maintenance', sa.Float(), nullable=True),
    sa.Column('assets', sa.Float(), nullable=True),
    sa.Column('liabilities', sa.Float(), nullable=True),
    sa.Column('commission_blocked', sa.Float(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('server', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('last_update_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
