"""create gap table and symbol table

Revision ID: 99c76da6b201
Revises: 
Create Date: 2024-02-04 16:46:27.338184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c76da6b201'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbolId', sa.Integer(), nullable=False),
    sa.Column('symbolName', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('initUntil', sa.String(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('baseAssetId', sa.Integer(), nullable=True),
    sa.Column('quoteAssetId', sa.Integer(), nullable=True),
    sa.Column('symbolCategoryId', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbolId')
    )
    time_data_gap_table = op.create_table('time_data_gap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(time_data_gap_table,
        [
            {
                'symbol': 'symbol_initiation',
                'start_date': '0',
                'end_date': '0',
                'timeframe': '0',
                'status': 'pending'
            },
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_data_gap')
    op.drop_table('symbols')
    # ### end Alembic commands ###
