"""Add user_profiles table

Revision ID: ad3e4fccc7c7
Revises: 6227e03f1315
Create Date: 2024-04-18 07:30:58.628543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3e4fccc7c7'
down_revision: Union[str, None] = '6227e03f1315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
