version: '3.8'
services:
  redis:
    build:
      context: ./redis
    ports:
      - 6379:6379
    networks:
      - my-network
  node:
    build: 
      context: ../modules/LiveDataCollector
    volumes:
      - ../modules/LiveDataCollector/src:/usr/src/app/src
    ports:
      - 3101:3000
    networks:
      - my-network
  # fastapi:
  #   build:
  #     context: ./api
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - timescaledb

  # timescaledb:
  #   image: timescale/timescaledb-ha:pg14-latest
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_DB: mydatabase
  #   volumes:
  #     - timescaledb-data:/var/lib/postgresql/data

  # airflow:
  #   image: apache/airflow
  #   environment:
  #     - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  #     - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://myuser:mypassword@postgres/mydb
  #     - AIRFLOW__CORE__LOAD_EXAMPLES=False
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - timescaledb

# volumes:
#   postgres-data:
#   timescaledb-data:
networks:
  my-network:
    driver: bridge
