"""init tables

Revision ID: d6d4e6be8533
Revises: 
Create Date: 2024-01-12 13:12:12.633665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6d4e6be8533'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fifteen_min_data',
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('pair_name', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'pair_name')
    )
    op.create_table('five_min_data',
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('pair_name', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'pair_name')
    )
    op.create_table('four_hour_data',
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('pair_name', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'pair_name')
    )
    op.create_table('one_day_data',
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('pair_name', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'pair_name')
    )
    op.create_table('one_hour_data',
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('pair_name', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'pair_name')
    )
    op.create_table('one_min_data',
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('pair_name', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'pair_name')
    )
    op.create_table('one_month_data',
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('pair_name', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'pair_name')
    )
    op.create_table('one_week_data',
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('pair_name', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'pair_name')
    )
    op.create_table('thirty_min_data',
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('pair_name', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'pair_name')
    )
    op.create_table('tick_data',
    sa.Column('pair_name', sa.String(length=10), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('bid', sa.Numeric(), nullable=True),
    sa.Column('ask', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('pair_name', 'time')
    )
    op.drop_index('forex_data_time_idx', table_name='forex_data')
    op.drop_table('forex_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forex_data',
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('closeout_bid', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('closeout_ask', sa.NUMERIC(), autoincrement=False, nullable=False)
    )
    op.create_index('forex_data_time_idx', 'forex_data', [sa.text('time DESC')], unique=False)
    op.drop_table('tick_data')
    op.drop_table('thirty_min_data')
    op.drop_table('one_week_data')
    op.drop_table('one_month_data')
    op.drop_table('one_min_data')
    op.drop_table('one_hour_data')
    op.drop_table('one_day_data')
    op.drop_table('four_hour_data')
    op.drop_table('five_min_data')
    op.drop_table('fifteen_min_data')
    # ### end Alembic commands ###
