"""fix TickData sympol string length

Revision ID: 89d33d90a55f
Revises: fbd2af89c258
Create Date: 2024-01-17 18:43:34.908779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d33d90a55f'
down_revision: Union[str, None] = 'fbd2af89c258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fifteen_min_data_time_idx', table_name='fifteen_min_data')
    op.drop_index('five_min_data_time_idx', table_name='five_min_data')
    op.drop_index('four_hour_data_time_idx', table_name='four_hour_data')
    op.drop_index('one_day_data_time_idx', table_name='one_day_data')
    op.drop_index('one_hour_data_time_idx', table_name='one_hour_data')
    op.drop_index('one_min_data_time_idx', table_name='one_min_data')
    op.drop_index('one_month_data_time_idx', table_name='one_month_data')
    op.drop_index('one_week_data_time_idx', table_name='one_week_data')
    op.drop_index('thirty_min_data_time_idx', table_name='thirty_min_data')
    op.alter_column('tick_data', 'pair_name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('tick_data_time_idx', table_name='tick_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tick_data_time_idx', 'tick_data', [sa.text('time DESC')], unique=False)
    op.alter_column('tick_data', 'pair_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.create_index('thirty_min_data_time_idx', 'thirty_min_data', [sa.text('time DESC')], unique=False)
    op.create_index('one_week_data_time_idx', 'one_week_data', [sa.text('time DESC')], unique=False)
    op.create_index('one_month_data_time_idx', 'one_month_data', [sa.text('time DESC')], unique=False)
    op.create_index('one_min_data_time_idx', 'one_min_data', [sa.text('time DESC')], unique=False)
    op.create_index('one_hour_data_time_idx', 'one_hour_data', [sa.text('time DESC')], unique=False)
    op.create_index('one_day_data_time_idx', 'one_day_data', [sa.text('time DESC')], unique=False)
    op.create_index('four_hour_data_time_idx', 'four_hour_data', [sa.text('time DESC')], unique=False)
    op.create_index('five_min_data_time_idx', 'five_min_data', [sa.text('time DESC')], unique=False)
    op.create_index('fifteen_min_data_time_idx', 'fifteen_min_data', [sa.text('time DESC')], unique=False)
    # ### end Alembic commands ###
