"""Add tick data table

Revision ID: bbb389eed8ac
Revises: 
Create Date: 2024-01-12 07:00:52.372711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbb389eed8ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forex_tick_data',
    sa.Column('pair_name', sa.String(length=10), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('bid', sa.Numeric(), nullable=True),
    sa.Column('ask', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('pair_name', 'time')
    )
    op.drop_index('forex_data_time_idx', table_name='forex_data')
    op.drop_table('forex_data')
    op.execute("SELECT create_hypertable('forex_tick_data', 'time')")
    # ### end Alembic commands ###
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forex_data',
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('closeout_bid', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('closeout_ask', sa.NUMERIC(), autoincrement=False, nullable=False)
    )
    op.create_index('forex_data_time_idx', 'forex_data', [sa.text('time DESC')], unique=False)
    op.drop_table('forex_tick_data')
    # ### end Alembic commands ###
