"""add source to TickData table

Revision ID: fbd2af89c258
Revises: d6d4e6be8533
Create Date: 2024-01-17 18:23:06.407218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd2af89c258'
down_revision: Union[str, None] = 'd6d4e6be8533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fifteen_min_data', sa.Column('source', sa.String(), nullable=True))
    op.add_column('five_min_data', sa.Column('source', sa.String(), nullable=True))
    op.add_column('four_hour_data', sa.Column('source', sa.String(), nullable=True))
    op.add_column('one_day_data', sa.Column('source', sa.String(), nullable=True))
    op.add_column('one_hour_data', sa.Column('source', sa.String(), nullable=True))
    op.add_column('one_min_data', sa.Column('source', sa.String(), nullable=True))
    op.add_column('one_month_data', sa.Column('source', sa.String(), nullable=True))
    op.add_column('one_week_data', sa.Column('source', sa.String(), nullable=True))
    op.add_column('thirty_min_data', sa.Column('source', sa.String(), nullable=True))
    op.add_column('tick_data', sa.Column('source', sa.String(), nullable=True))

    tables_to_convert = [
        'one_min_data', 'five_min_data', 'fifteen_min_data',
        'thirty_min_data', 'one_hour_data', 'four_hour_data',
        'one_day_data', 'one_week_data', 'one_month_data',
        'tick_data'
    ]
    for table in tables_to_convert:
        op.execute(f"SELECT create_hypertable('{table}', 'time');")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tick_data', 'source')
    op.drop_column('thirty_min_data', 'source')
    op.drop_column('one_week_data', 'source')
    op.drop_column('one_month_data', 'source')
    op.drop_column('one_min_data', 'source')
    op.drop_column('one_hour_data', 'source')
    op.drop_column('one_day_data', 'source')
    op.drop_column('four_hour_data', 'source')
    op.drop_column('five_min_data', 'source')
    op.drop_column('fifteen_min_data', 'source')
    # ### end Alembic commands ###
